steps:
- name: node
  entrypoint: npm
  args: ['ci']
- name: node
  entrypoint: npm
  args: ['run', 'build']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west2-docker.pkg.dev/${PROJECT_ID}/lab-docker-repo', '.']
images: ['europe-west2-docker.pkg.dev/${PROJECT_ID}/lab-docker-repo']